### ISSUE TITLE
Known type information should be available in the propositions (pos/neg filters).

### ISSUE THREAD

**Issue by jsmaniac** [racket/typed-racket#429]
### What version of Racket are you using?

6.4.0.5 (20160914-62f5b2c)
### What program did you run?

The following code builds a `(stx-car/c nested-c)` contract, which returns the result of calling `nested-c` (usually a boolean) on the `stx-car` of `v`. I wanted to add some type propositions to make it clear that the result is non-false iff `v` is a `(Syntaxof (Pairof Pos Any))`, where `Pos` is the positive proposition for `nested-c`. The goal is to tell TR that `((stx-car/c number?) v)` is true iff `v` is `(Syntaxof (Pairof Number Any))`.

```
#lang typed/racket

(: stx-car/c (∀ (Result Pos Neg) (→ (→ Any Result : #:+ Pos #:- Neg)
                                    (→ Any (U #f Result)
                                       : #:+ (Syntaxof (Pairof Pos Any))))))
(define ((stx-car/c nested-c) v)
  (if (syntax? v)
      (if (pair? (syntax-e v))
          (let ([result (nested-c (car (syntax-e v)))])
            (if result
                (begin (ann v (Syntaxof (Pairof Pos Any)))
                       result)
                #f))
          #f)
      #f))
```
### What should have happened?

The program should typecheck. The information concerning `v` is known, since the expression `(ann v (Syntaxof (Pairof Pos Any)))` typechecks witout any problem, but that information is not propagated to the `#:+` filter.
### If you got an error message, please include it here.

The error message shows that TR has all the information needed in small pieces, but it does not combine them. Also, since the path-elem is restricted to `car` and `cdr`, one can only write `#:+ (Type @ (car-or-cdr …) v)`, but not e.g. `#:+ (Type @ (car syntax) v)`, so it's impossible to simply tell TR to use the filters it has inferred, because they can't be expressed syntactically.

```
Type Checker: type mismatch;
 mismatch in proposition
  expected: (((Syntaxof (Pairof Pos Any)) @ v) | Top)
  given: ((AndProp ((Syntaxof Any) @ v) ((Pairof Any Any) @ (syntax) v) (Pos @ (car syntax) v)) | (OrProp (! (Syntaxof Any) @ v) (! (Pairof Any Any) @ (syntax) v) (Neg @ (car syntax) v))) in: (if (syntax? v) (if (pair? (syntax-e v)) (let ((result (c (car (syntax-e v))))) (if result (begin (ann v (Syntaxof (Pairof Pos Any))) result) #f)) #f) #f)
```

**Comment by andmkent** [comment]
Just an FYI/update -- I'm working on a PR that includes a fix for this. Will post a link when it's closer to being ready.

**Comment by pnwamk** [comment]
fixed via be155fa3e3236caa93ef927e205c45b00d6d6e6e

**Comment by jsmaniac** [comment]
I just upgraded to the 6.8.0.1 pre-release a couple of days ago, and it seems the example file above still doesn't typecheck, with the same error (or maybe there was a regression? I thought I had tested this after @pnwamk's patch)

I also encountered the problem on a somewhat simpler example:

```racket
#lang typed/racket
(: p? (∀ (A D) (→ (Pairof Any Any)
                  Boolean
                  : (Pairof Number String))))
(define (p? v)
  (if (number? (car v))
      (if (string? (cdr v))
          #t
          #f)
      #f))
```

which fails with the error:
```
Type Checker: type mismatch;
 mismatch in proposition
  expected: (((Pairof Number String) @ v) | (! (Pairof Number String) @ v))
  given: ((AndProp (Number @ (car) v) (String @ (cdr) v)) | (OrProp (! String @ (cdr) v) (! Number @ (car) v)))
```

**Comment by pnwamk** [comment]
Sorry about closing it prematurely -- I think we got closer to it type checking, but there's another small tweak I need to make to get us there. Note to self: off the top of my head, I _think_ this issue would be resolved by using a stronger version of `contradictory?` for the `combine-props` metafunction. I'll have to experiment and report.

**Comment by stamourv** [comment]
@jsmaniac: Nitpick: 6.8.0.1 is not a pre-release; it's a build from the master branch. There will most likely be code that is in 6.8.0.1 that is not in 6.8. And fixes that @pnwamk develops for this issue may not be in 6.8 either.

**Comment by jsmaniac** [comment]
Both the initial larger file and the subsequent smaller example seem to work, so I'm closing this now.
